services:
  - type: web
    name: despedida-soltero
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RESET_KEY
        value: despedida2025
